export const Question = [
    {
      prompt: "In what year did the Great October Socialist Revolution take place?",
      optionA: 1917,
      optionB: 1923,
      optionC: 1914,
      optionD: 1920,
      Answer: "optionA",
    },
    {
      prompt: "What is the largest lake in the world?",
      optionA: "Caspian Sea",
      optionB: "Baikal",
      optionC: "Lake Superior",
      optionD: "Ontario",
      Answer: "optionA",
    },
    {
      prompt: "Who developed the theory of general relativity?",
      optionA: "Isaac Newton",
      optionB: "Albert Einstein",
      optionC: "Galileo Galilei",
      optionD: "Marie Curie",
      Answer: "optionB",
    },
    {
      prompt: "Which planet is known as the Red Planet?",
      optionA: "Earth",
      optionB: "Mars",
      optionC: "Venus",
      optionD: "Jupiter",
      Answer: "optionB",
    },
    {
      prompt: "Who painted the Mona Lisa?",
      optionA: "Vincent van Gogh",
      optionB: "Leonardo da Vinci",
      optionC: "Pablo Picasso",
      optionD: "Claude Monet",
      Answer: "optionB",
    },
    {
      prompt: "What is the capital of Japan?",
      optionA: "Seoul",
      optionB: "Tokyo",
      optionC: "Beijing",
      optionD: "Bangkok",
      Answer: "optionB",
    },
    {
      prompt: "Which element has the chemical symbol 'O'?",
      optionA: "Oxygen",
      optionB: "Gold",
      optionC: "Osmium",
      optionD: "Hydrogen",
      Answer: "optionA",
    },
    {
      prompt: "What is the tallest mountain in the world?",
      optionA: "Mount Kilimanjaro",
      optionB: "Mount Everest",
      optionC: "K2",
      optionD: "Denali",
      Answer: "optionB",
    },
    {
      prompt: "Which country is known as the Land of the Rising Sun?",
      optionA: "China",
      optionB: "Japan",
      optionC: "Thailand",
      optionD: "India",
      Answer: "optionB",
    },
    {
      prompt: "Which language is primarily spoken in Brazil?",
      optionA: "Spanish",
      optionB: "Portuguese",
      optionC: "French",
      optionD: "English",
      Answer: "optionB",
    }
  ];
  